// Write your code here

// DO NOT WRITE BELOW THIS LINE! This will test that you did it correctly

Sandbox.test(
  "Challenge Complete",
  pkgBuffer.toString("base64") ===
    "REJQRgIAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAkAAAAAAAAAAAAAAAAAAAAAwAAAIkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAeJwLDnHyYWVgYGSAAT4gLrmwXJ2Bl8EjNScnX0ehPL8oJ0URAHn+B/IAAAAA2lcFIgAAAICBBvkAXNxOkGAAAAApAACAKQAAAEJaAQA="
);
